services:
  db:
    container_name: $PG_CONTAINER
    image: postgres
    command:
      -c ssl=on 
      -c ssl_cert_file=/temp/ssl/server.crt
      -c ssl_key_file=/temp/ssl/server.key
      -c ssl_ca_file=/temp/ssl/root.crt
    environment:
      - POSTGRES_DB=$PG_DB
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PWD
    build:
      context: .
      args:
        - PG_DB=${PG_DB}
        - PG_TABLE=${PG_TABLE}
    ports:
          - "5432:5432"
    restart: unless-stopped

networks:
  pgdata2:


