version: "3.4"
services:
  db:
    container_name: $PG_CONTAINER
    image: postgres
    environment:
      - POSTGRES_DB=$PG_DB
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PWD
    build:
      context: .
      args:
        - PG_DB=${PG_DB}
        - PG_TABLE=${PG_TABLE}
    ports:
          - "5432:5432"
    restart: unless-stopped

    # Copy-data on- docker-entrypoint-initdb 
    # volumes:
       # seed.sql 
       #   Passing variables to seed.sql means it needs to be provided in Dockerfile build
       #   Dockerfile Adds this instead, and then runs a bashscript to replace arg variables
       #- ./scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql

       # postgressql_data
       #   Copy data in Docker file to prevent unnecessary bind mount
       #   Then run this initscript: 
       # - ./postgresql_data:/temp
       # - ./scripts/copy-data.sh:/docker-entrypoint-initdb.d/copy-data.sh:ro
       # - ./scripts/sym-conf.sh:/docker-entrypoint-initdb.d/sym-conf.sh:ro

networks:
  pgdata2:


